FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt -y install software-properties-common

RUN apt-get -y install curl gnupg 

RUN add-apt-repository ppa:ondrej/php && \
    apt-get update

RUN apt -y install php7.4
RUN apt -y install libapache2-mod-php7.4
RUN apt -y install php7.4-mysql
RUN phpenmod pdo_mysql
#RUN apt install php-mysql

# Install CGI and CLI if not installed by default
RUN apt -y install php7.4-common php7.4-cgi php7.4-cli vim

# Install CURL and JSON extensions
RUN apt -y install php7.4-curl php7.4-json php7.4-zip

# Install PHP Redis
RUN apt -y install php7.4-redis

# Install PHP GD and Imagick
# RUN apt install php7.4-gd php-imagick

# Multibyte String, Internationalization and Spell Check
RUN apt -y install php7.4-mbstring php7.4-intl php7.4-pspell php7.4-xml php7.4-bcmath

# Emails
#RUN apt -y install php7.4-imap

# SQLite Database
#RUN apt install php7.4-sqlite3 

# Tidy and XML RPC
#RUN apt install php7.4-tidy php7.4-xmlrpc

# Excel
#RUN apt -y install php7.4-xsl
# Opcache
#RUN apt -y install php7.4-opcache


RUN a2enmod rewrite
RUN a2enmod ssl
RUN a2enmod proxy

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install --yes nodejs
RUN node -v
RUN npm -v
RUN npm i -g nodemon
RUN nodemon -v

#RUN docker-php-ext-install intl
#COPY --chown=www-data:www-data . /var/www/html/ 
COPY ./vhost.conf /etc/apache2/sites-available/000-default.conf
#COPY ./config/custom_php.ini /etc/php/7.4/apache2/conf.d/custom_php.ini  

#WORKDIR /var/www/html
#ENTRYPOINT service apache2 start
#CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
#CMD ["node", './node/redis.js', 'initial' ]
#CMD ["node", './node/redis-pusher.js', 'initial' ]
